/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Pedaleira;
import dao.Pedaleira_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class JDlgPedaleira extends javax.swing.JDialog {

    private boolean incluindo;
    /**
     * Creates new form JDlgPedaleira
     */
    public JDlgPedaleira(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        desabilitar();
        setLocationRelativeTo(null);
        setTitle("Pedaleira");
    }
    
    public void habilitar(){
        jTxtCodPedal.setEnabled(true);
        jTxtPedalEx.setEnabled(true);
        jTxtLoop.setEnabled(true);
        jTxtIr.setEnabled(true);
        jTxtSaida.setEnabled(true);
        
       jBtnConfirmar.setEnabled(true);
       jBtnCancelar.setEnabled(true);

       jBtnPesquisar.setEnabled(false);
       jBtnAlterar.setEnabled(false);
       jBtnIncluir.setEnabled(false);
       jBtnExcluir.setEnabled(false);
    };
    
    public void desabilitar(){
        jTxtCodPedal.setEnabled(false);
        jTxtPedalEx.setEnabled(false);
        jTxtLoop.setEnabled(false);
        jTxtIr.setEnabled(false);
        jTxtSaida.setEnabled(false);
       
       jBtnConfirmar.setEnabled(false);
       jBtnCancelar.setEnabled(false);

       jBtnPesquisar.setEnabled(true);
       jBtnAlterar.setEnabled(true);
       jBtnIncluir.setEnabled(true);
       jBtnExcluir.setEnabled(true);
    };

    public void limparCampos(){
    jTxtCodPedal.setText("");
    jTxtPedalEx.setText("");
    jTxtLoop.setText("");
    jTxtIr.setText("");
    jTxtSaida.setText("");
    }
        
    public Pedaleira viewBean(){
    Pedaleira pedaleira = new Pedaleira();
    int id = Integer.valueOf(jTxtCodPedal.getText());
    pedaleira.setIdPedaleira(id);
    pedaleira.setPedalExpressão(jTxtPedalEx.getText());
    pedaleira.setLoop(jTxtLoop.getText());
    pedaleira.setIr(jTxtIr.getText());
    pedaleira.setSaidaUsb(jTxtSaida.getText());
    
    return pedaleira;
    };
    
    public void beanView(Pedaleira pedaleira){
    String Valor = String.valueOf(pedaleira.getIdPedaleira());
    jTxtCodPedal.setText(Valor);
    jTxtPedalEx.setText(pedaleira.getPedalExpressão());
    jTxtLoop.setText(pedaleira.getLoop());
    jTxtIr.setText(pedaleira.getIr());
    jTxtSaida.setText(pedaleira.getSaidaUsb());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodPedal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtPedalEx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtLoop = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtIr = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtSaida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCancelar.setText("cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmar.setText("confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo da Pedaleira");

        jLabel2.setText("Pedal de Expressão");

        jLabel3.setText("Loop");

        jLabel4.setText("IR");

        jLabel5.setText("Saida USB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTxtSaida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(jTxtIr, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtLoop, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtPedalEx, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTxtCodPedal, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodPedal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPedalEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtLoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jTxtIr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnIncluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
    desabilitar();
    jBtnAlterar.setEnabled(true);
    jBtnExcluir.setEnabled(true);
    jBtnPesquisar.setEnabled(true);
    jBtnIncluir.setEnabled(true);

    limparCampos();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
//    habilitar();
//    String resp = JOptionPane.showInputDialog(null, "Entre com o codigo(chave primaria)");
//    Pedaleira_DAO pedaleira_DAO = new Pedaleira_DAO();
//    int id = Integer.valueOf(resp);
//    Pedaleira pedaleira = (Pedaleira) pedaleira_DAO.list(id);//o list retorna o bean, o list pega o bean e transforma em  objeto
//    beanView(pedaleira);
JDlgPedaleiraPesquisa jDlgPedaleiraPesquisa = new JDlgPedaleiraPesquisa(null, true);
jDlgPedaleiraPesquisa.setTelaAnterior(this);
jDlgPedaleiraPesquisa.setVisible(true);

    jBtnAlterar.setEnabled(true);
    jBtnPesquisar.setEnabled(true);
    jBtnCancelar.setEnabled(true);
    jBtnConfirmar.setEnabled(false);
    jBtnExcluir.setEnabled(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
    habilitar();
    limparCampos();
    incluindo = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
    habilitar();  
    incluindo = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
    habilitar();
    int resp =  JOptionPane.showConfirmDialog(null, "Deseja excluir o registro",
            "confirmar", JOptionPane.YES_NO_OPTION);
    if (resp == JOptionPane.YES_OPTION){
    Pedaleira pedaleira = viewBean();
    Pedaleira_DAO pedaleira_DAO = new Pedaleira_DAO();
    pedaleira_DAO.delete(pedaleira);
    
    } else{
    JOptionPane.showMessageDialog(null, "Exclusão cancelada ",
    "alerta", 2
    );
    }
        limparCampos();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
    Pedaleira pedaleira = viewBean();
    Pedaleira_DAO pedaleira_DAO = new Pedaleira_DAO();
    if (incluindo == true){
    pedaleira_DAO.insert(pedaleira);
    } else {
    pedaleira_DAO.update(pedaleira);}
    desabilitar();
    limparCampos(); 
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgPedaleira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgPedaleira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgPedaleira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgPedaleira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgPedaleira dialog = new JDlgPedaleira(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxtCodPedal;
    private javax.swing.JTextField jTxtIr;
    private javax.swing.JTextField jTxtLoop;
    private javax.swing.JTextField jTxtPedalEx;
    private javax.swing.JTextField jTxtSaida;
    // End of variables declaration//GEN-END:variables
}
