/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Guitarra;
import dao.Guitarra_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class JDlgGuitarra extends javax.swing.JDialog {

    private boolean incluindo;
    /**
     * Creates new form JDlgGuitarra
     */
    public JDlgGuitarra(java.awt.Frame parent, boolean modal) {
            super(parent, modal);
        initComponents();
        desabilitar();
        setLocationRelativeTo(null);
        setTitle("Guitarras");
    }
    
    public void habilitar(){
       jTxtCodGuitarra.setEnabled(true);
       jCboTipo.setEnabled(true);
       jTxtTrastes.setEnabled(true);
       jTxtModelo.setEnabled(true);
       jTxtCaptadores.setEnabled(true);
       jTxtPonte.setEnabled(true);
       jTxtCanhoto.setEnabled(true);
        
       jBtnConfirmar.setEnabled(true);
       jBtnCancelar.setEnabled(true);

       jBtnPesquisar.setEnabled(false);
       jBtnAlterar.setEnabled(false);
       jBtnIncluir.setEnabled(false);
       jBtnExcluir.setEnabled(false);};
    
    public void desabilitar(){
       jTxtCodGuitarra.setEnabled(false);
       jCboTipo.setEnabled(false);
       jTxtTrastes.setEnabled(false);
       jTxtModelo.setEnabled(false);
       jTxtCaptadores.setEnabled(false);
       jTxtPonte.setEnabled(false);
       jTxtCanhoto.setEnabled(false);
        
       jBtnConfirmar.setEnabled(false);
       jBtnCancelar.setEnabled(false);

       jBtnPesquisar.setEnabled(true);
       jBtnAlterar.setEnabled(true);
       jBtnIncluir.setEnabled(true);
       jBtnExcluir.setEnabled(true);};
    
    public void limparCampos(){
    jTxtCodGuitarra.setText("");
    jCboTipo.setSelectedIndex(-1);
    jTxtTrastes.setText("");
    jTxtModelo.setText("");
    jTxtCaptadores.setText("");
    jTxtPonte.setText("");
    jTxtCanhoto.setText("");
    };
    
    public Guitarra viewBean(){
    Guitarra guitarra = new Guitarra();
    int id = Integer.valueOf(jTxtCodGuitarra.getText());
    guitarra.setIdProdutos(id);
    if (jCboTipo.getSelectedIndex()==0){
    guitarra.setTipo("Strato");
    }else if (jCboTipo.getSelectedIndex()==1){
    guitarra.setTipo("LesPaul");
    }else {
    guitarra.setTipo("Outro");};
    guitarra.setTrastes(jTxtTrastes.getText());
    guitarra.setModelo(jTxtModelo.getText());
    guitarra.setCaptadores(jTxtCaptadores.getText());
    guitarra.setPonte(jTxtPonte.getText());
    guitarra.setCanhotoDestro(jTxtCanhoto.getText());
    return guitarra;    
    };
    
    public void beanView(Guitarra guitarra){
    String valor = String.valueOf(guitarra.getIdProdutos());
    jTxtCodGuitarra.setText(valor);
    if(guitarra.getModelo()=="Strato"){
    jCboTipo.setSelectedIndex(0);
    }else if(guitarra.getModelo()=="LesPaul"){
    jCboTipo.setSelectedIndex(1);    
    }else{
    jCboTipo.setSelectedIndex(2);};
    jTxtTrastes.setText(guitarra.getTrastes());
    jTxtModelo.setText(guitarra.getModelo());
    jTxtCaptadores.setText(guitarra.getCaptadores());
    jTxtPonte.setText(guitarra.getPonte());
    jTxtCanhoto.setText(guitarra.getCanhotoDestro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodGuitarra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtCaptadores = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtPonte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtCanhoto = new javax.swing.JTextField();
        jTxtTrastes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnIncluir.setText("incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnAlterar.setText("alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnConfirmar.setText("confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnCancelar.setText("cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setText("pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo da Guitarra");

        jLabel2.setText("Tipo de Guitarra");

        jCboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "strato", "lesPaul", "outro" }));

        jLabel3.setText("Trastes");

        jLabel4.setText("Modelo");

        jLabel5.setText("Captadores");

        jLabel6.setText("Ponte");

        jLabel7.setText("Canhoto ou Destro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar)
                        .addGap(10, 10, 10)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtPonte, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTxtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCboTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                                        .addComponent(jTxtCodGuitarra, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jTxtCaptadores)
                            .addComponent(jTxtCanhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTxtTrastes))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodGuitarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTrastes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCaptadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPonte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCanhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar)
                    .addComponent(jBtnIncluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
  habilitar();
    limparCampos();
    incluindo = true;
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
    habilitar();  
    incluindo = false;
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
   habilitar();
    int resp =  JOptionPane.showConfirmDialog(null, "Deseja excluir o registro",
            "confirmar", JOptionPane.YES_NO_OPTION);
    if (resp == JOptionPane.YES_OPTION){
    Guitarra guitarra = viewBean();
    Guitarra_DAO guitarra_DAO = new Guitarra_DAO();
    guitarra_DAO.delete(guitarra );
    
    } else{
    JOptionPane.showMessageDialog(null, "Exclusão cancelada ",
    "alerta", 2
    );
    }
        limparCampos();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
    Guitarra guitarra = viewBean();
    Guitarra_DAO guitarra_DAO = new Guitarra_DAO();
    if (incluindo == true){
    guitarra_DAO.insert(guitarra);
    } else {
    guitarra_DAO.update(guitarra);}
    desabilitar();
    limparCampos();  
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
    desabilitar();
    jBtnAlterar.setEnabled(true);
    jBtnExcluir.setEnabled(true);
    jBtnPesquisar.setEnabled(true);
    jBtnIncluir.setEnabled(true);

    limparCampos();
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
// habilitar();
//    String resp = JOptionPane.showInputDialog(null, "Entre com o codigo(chave primaria)");
//    Guitarra_DAO guitarra_DAO = new Guitarra_DAO();
//    int id = Integer.valueOf(resp);
//    Guitarra guitarra = (Guitarra) guitarra_DAO.list(id);//o list retorna o bean, o list pega o bean e transforma em  objeto
//    beanView(guitarra);
JDlgGuitarraPesquisa jDlgGuitarraPesquisa = new JDlgGuitarraPesquisa(null, true);
jDlgGuitarraPesquisa.setTelaAnterior(this);
jDlgGuitarraPesquisa.setVisible(true);
    jBtnAlterar.setEnabled(true);
    jBtnPesquisar.setEnabled(true);
    jBtnCancelar.setEnabled(true);
    jBtnConfirmar.setEnabled(false);
    jBtnExcluir.setEnabled(true);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgGuitarra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgGuitarra dialog = new JDlgGuitarra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTxtCanhoto;
    private javax.swing.JTextField jTxtCaptadores;
    private javax.swing.JTextField jTxtCodGuitarra;
    private javax.swing.JTextField jTxtModelo;
    private javax.swing.JTextField jTxtPonte;
    private javax.swing.JTextField jTxtTrastes;
    // End of variables declaration//GEN-END:variables
}
